CT_i18n = []
CT_i18n[0] = CT_i18n[0] || 'To record this video using your mobile phone please visit <<url>> in your mobile browser'
CT_i18n[1] = CT_i18n[1] || '<img class="[ svg icon icon--iconed--xxlarge icon--stroke icon--responsive ][ color-light ]" src="icons/warning.svg"> Tu celular no soporta la carga de video'
CT_i18n[2] = CT_i18n[2] || '<img class="[ svg icon icon--iconed--xxlarge icon--stroke icon--responsive ][ color-light ]" src="icons/warning.svg"> Por favor asegúrate de tener Flash Player 11 o superior instalado'
CT_i18n[3] = CT_i18n[3] || '<img class="[ svg icon icon--iconed--xxlarge icon--stroke icon--responsive ][ color-light ]" src="icons/warning.svg"> No se puede inscrustar la cámara, por favor asegúrate de tener Flash Player 11 o superior instalado'
CT_i18n[4] = CT_i18n[4] || 'selecciona un método para enviar tu video'
CT_i18n[5] = CT_i18n[5] || 'grabar desde webcam'
CT_i18n[6] = CT_i18n[6] || 'subir un archivo'
CT_i18n[7] = CT_i18n[7] || 'grabar desde tu celular'
CT_i18n[8] = CT_i18n[8] || 'Saluda a la cámara'
CT_i18n[9] = CT_i18n[9] || 'Grabando en…'
CT_i18n[10] = CT_i18n[10] || 'Subiendo…'
CT_i18n[11] = CT_i18n[11] || '<a class="[ btn btn-primary btn--auto ]">Haz clic para dejar de grabar</a>'
CT_i18n[12] = CT_i18n[12] || '<a class="[ btn btn-primary btn--auto ]">Haz clic para continuar</a>'
CT_i18n[13] = CT_i18n[13] || 'Aceptar'
CT_i18n[14] = CT_i18n[14] || 'Volver a Grabar'
CT_i18n[15] = CT_i18n[15] || 'Ver Video'
CT_i18n[16] = CT_i18n[16] || 'por favor espera mientras subimos el video'
CT_i18n[17] = CT_i18n[17] || 'Video Publicado'
CT_i18n[18] = CT_i18n[18] || 'Escribe tu <b>número de celular</b> y te enviarémos un link para grabar en él.'
CT_i18n[19] = CT_i18n[19] || 'Enviar link móvil'
CT_i18n[20] = CT_i18n[20] || 'cancelar'
CT_i18n[21] = CT_i18n[21] || 'Checa tu celular para instrucciones de como grabar'
CT_i18n[22] = CT_i18n[22] || 'o dirije tu navegador móvil a'
CT_i18n[23] = CT_i18n[23] || 'arrastra aquí el video para subir'
CT_i18n[24] = CT_i18n[24] || 'mandando tu mensaje'
CT_i18n[25] = CT_i18n[25] || 'por favor escribe tu número celular'
CT_i18n[26] = CT_i18n[26] || 'no es un número de celular válido'
CT_i18n[27] = CT_i18n[27] || 'No pudimos enviarte el SMS.'
CT_i18n[28] = CT_i18n[28] || '<img class="[ svg icon icon--iconed--xxlarge icon--stroke icon--responsive ][ color-light ]" src="icons/warning.svg"> No se encontro la cámara'
CT_i18n[29] = CT_i18n[29] || '<img class="[ svg icon icon--iconed--xxlarge icon--stroke icon--responsive ][ color-light ]" src="icons/warning.svg"> No se encontró ningún micrófono'
CT_i18n[30] = CT_i18n[30] || '<img class="[ svg icon icon--iconed--xxlarge icon--stroke icon--responsive ][ color-light ]" src="icons/warning.svg"> Acceso a la cámara fue denegado'
CT_i18n[31] = CT_i18n[31] || '<img class="[ svg icon icon--iconed--xxlarge icon--stroke icon--responsive ][ color-light ]" src="icons/warning.svg"> Se perdió la conexión con el servidor'
CT_i18n[32] = CT_i18n[32] || '<img class="[ svg icon icon--iconed--xxlarge icon--stroke icon--responsive ][ color-light ]" src="icons/warning.svg"> La reproducción no funcionó'
CT_i18n[33] = CT_i18n[33] || '<img class="[ svg icon icon--iconed--xxlarge icon--stroke icon--responsive ][ color-light ]" src="icons/warning.svg"> No se pudo conectar'
CT_i18n[34] = CT_i18n[34] || '<img class="[ svg icon icon--iconed--xxlarge icon--stroke icon--responsive ][ color-light ]" src="icons/warning.svg"> No se puedo publicar tu grabación.'
CT_i18n[35] = CT_i18n[35] || '<img class="[ svg icon icon--iconed--xxlarge icon--stroke icon--responsive ][ color-light ]" src="icons/warning.svg"> No se puede enviar la información de la forma.'
CT_i18n[36] = CT_i18n[36] || 'Subiendo video'
CT_i18n[37] = CT_i18n[37] || 'Reproducción de video de búfer'
CT_i18n[38] = CT_i18n[38] || 'Guardando video…'
CT_i18n[39] = CT_i18n[39] || 'conectando…'
CT_i18n[40] = CT_i18n[40] || 'negociando la firewall…'
CT_i18n[41] = CT_i18n[41] || 'Parece que tu navegador detuvo la grabación, haz clic en el icono de <em>play</em> para reanudarla'